### ISSUE TITLE
Make more things require dark metal

### ISSUE THREAD

**Issue by RichPrune** [chocolate-edition/Chocolate-Edition#134]
Soul forge should be made with dark metal, and dark metal should be block swapped with dark iron. Make the recipe for dark metal ingot require corruption. Make corruption craft corrupted wart, blade, shield, stone variants like black argilite(w seeds of chaos), grimstone(w voidquartz)

**Comment by guyperson0** [comment]
How is Dark Iron getting more cucked than it already is

**Comment by guyperson0** [comment]
Made some changes because necessary:
- Dark Metal Ingot is now smithed using Dark Iron + Dark Metal Pile because Dark Iron requires corruption to begin with and let's be honest we gotta give that thing a use
- Stone variants shouldn't use two different "catalyst" items because we usually want them to be able to surround one item with 8 stone for 8 output, so black argillite just uses a seed of chaos and grimstone just uses one voidquartz and neither use corruption. If you really want to inconvenience people for some reason you can change that back.
- Corrupted Blade and Shield done
- Soul Forge done
