### ISSUE TITLE
QBO - Final Chapter

### ISSUE THREAD

**Issue by GildedToxin** [chocolate-edition/Chocolate-Edition#48]

**Comment by guyperson0** [comment]
- All quests rewritten from original, which were copy-pasted directly from the Google Doc and did not necessarily reflect the mod's actual implementation in the pack
- All quests given rewards
- Dimensional Carver and Shattered Dimensional Carver quests merged
- "Where it all began" changed from checkmark quest to location quest, now triggers upon finding Rundown House
- "Summon Entity" quest renamed to "Summon Wither Storm" for clarity and changed from checkmark quest to advancement quest, completes upon triggering the "Nothing Built Can Last Forever" advancement (summoning Wither Storm)
- "Run" quest changed from checkmark quest to advancement quest, completes upon triggering "Harbinger of Cataclysmic Fates" (encountering Withered Symbiont)
- "Craft a golden apple stew" quest requirements now optionally require the golden apple stew's ingredients instead of them being mandatory; only the actual stew itself is required to complete
- Super TNT and Formidibomb quests merged, Super TNT is only required optionally in case the player directly crafts from Super TNT to Formidibomb without closing the crafting GUI
- Wither Storm playing dead quest converted from checkmark to advancement, requiring both "The Strong Grow Weak..." (blowing up Wither Storm) and "...The Weakened Arising Stronger" (Wither Storm revives)
- Command Block Tool quest now uses OR filter
- Ender Pearl crossbow quest merged with Enter Bowels quest, Ender Pearl and Crossbow made optional as they are not necessary for entering the Bowels
- Added a Phase Check quest that runs a command to get the Wither Storm's current phase for convenience.

**Comment by GildedToxin** [comment]
We need to remove images that we dont have rights to
