### ISSUE TITLE
make chemical x more easily craftable, and/or increase its conversion rate

### ISSUE THREAD

**Issue by Jonah-Hansen** [chocolate-edition/Chocolate-Edition#510]
waiting for mutant spawns when youre finally ready to face them is one of the most frustrating parts for me early game. I would like to see chemical x more easily craftable so its possible to fight mutants on your own terms

or make formula 7 work on the early mutants? idk something like that

we could edit the recipe to use zombie skeleton or creeper head (can get from charged creeper explosion, beheading weapons or from some structures)

**Comment by Drun555** [comment]
I agree 100%. Even fishing Neptune's bounty was more satisfying,

After several hours, I finally met one mutant zombie (and, of course, died to him). Then I just rage-cheated and give myself mutant zombie egg spawner. 

Right now, I'll underline this, _it's a first eye in the list_. To spawn one by yourself, you'll need alchemy (requires Stage 1) and Mutant Skeleton / Mutant Creeper kill. Because Clockwork Eye is unaccessible at Stage 0, we have to get Exotic / Rogue / Guardian eye first:
- (Rogue) Mutant Creeper kill, and it has same issue as Mutant Zombie
- (Exotic) Praying for Neptune's bounty. It has 0.5% chance of appearing. Not sure if it scales with Luck attribute, but I hope so. It was a nightmare even with it.
- (Guardian) Seems like most easy one to get?

Then you'll have to get to the Nether, get Blazing powder / some other gear, and finally create one first potion - if your third eye was Rogue. If not, you'll have to wait another Mutant mob to spawn.

Overall, it has to be more easy craftable, because right now it's:
- very time consuming in term of waiting it to spawn in controllable place (I don't think you'll be able to kill one without cheesing at this stage)
- or it's a long way to get Stage 1 first and then hunting any other Mutant mob

Back in the old good days, original recipe was that simple:
![LVzvK](https://github.com/user-attachments/assets/22421207-feee-4c93-90d2-fe9b6b65adad)

And I think it's really more suitable for 'Easy' eyes.

**Comment by Crisptain** [comment]
> alchemy (requires Stage 1)
> Clockwork Eye is unaccessible at Stage 0
These are both false, brewing stands are easy to come across and blaze powder to fuel them can either be crafted or looted from a common structure (the wells full of lava from born in chaos, which incidentally can also straight up have blaze rods). As for the Clockwork Eye, the Blaze Burner has a custom recipe specifically to make it obtainable pre-nether, and quartz can be obtained by tearing down meadow villages, using a single soul block to haunt sand into soul sand and wash that, or you can skip the middle man and find rose quartz directly in certain structures. If you don't see the overworld-accessible recipes for either blaze powder or the blaze burner something is probably wrong with your scripts.

**Comment by GildedToxin** [comment]
Closed by #610
